# Generated by Django 2.2.4 on 2019-08-16 15:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hashtag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=140, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Mention',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('in_reply_to_status_id', models.BigIntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Picture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('media_id', models.BigIntegerField()),
                ('image', models.ImageField(upload_to='images')),
                ('image_original_url', models.URLField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TwitterUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.BigIntegerField(db_index=True, unique=True)),
                ('screen_name', models.CharField(max_length=255)),
                ('is_target', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', models.FileField(upload_to='videos')),
                ('video_original_url', models.URLField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tweet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tweet_id', models.BigIntegerField(unique=True)),
                ('created_at', models.DateTimeField()),
                ('text', models.TextField(null=True)),
                ('retweet_id', models.BigIntegerField(null=True)),
                ('hashtags', models.ManyToManyField(related_name='tweets', to='tweet.Hashtag')),
                ('images', models.ManyToManyField(related_name='tweets', to='tweet.Picture')),
                ('mention', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tweets', to='tweet.Mention')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tweets', to='tweet.TwitterUser')),
                ('videos', models.ManyToManyField(related_name='tweets', to='tweet.Video')),
            ],
        ),
        migrations.AddField(
            model_name='mention',
            name='twitter_users',
            field=models.ManyToManyField(related_name='mention_tweets', to='tweet.TwitterUser'),
        ),
    ]
